name: infinity_youtube
description: "a youtube video player for infinity"
publish_to: "none"
# --------------------------------------------------------------------------------
# THE_APP_VERSION
version: 0.0.2
# --------------------------------------------------------------------------------
environment:
  sdk: ">=3.8.1 <4.0.0"
# --------------------------------------------------------------------------------
dependencies:
  clipboard: ^2.0.2
  flutter:
    sdk: flutter
  # ------------------------------------
  # NO NEED - FOR REFERENCE
#  flutter_launcher_icons: ^0.14.4
#  launcher_name: ^1.0.2
  # ------------------------------------
  go_router: ^15.1.2
  no_screenshot: ^0.3.2-beta.3
  image: ^4.5.4
  youtube_player_flutter: ^9.1.1
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  youtube_explode_dart: ^2.5.2
  win32: ^5.14.0
  ffi: ^2.1.4
  app_links: ^6.4.1
  win32_registry: ^2.1.0
  # media_kit_libs_audio: ^1.0.6
  # media_kit_libs_android_video: ^1.3.7
  # ------------------------------------
dev_dependencies:
  msix: ^3.16.8
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  # ------------------------------------
# Windows only (packaged app)
msix_config:
  display_name: Infinity YouTube
  msix_version: 1.0.0.0
  protocol_activation: infinity
  app_uri_handler_hosts: www.infinity.com, infinity.com
  # ------------------------------------
#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/logo_plain.jpg"
#  adaptive_icon_background: "#5943e9"
#  adaptive_icon_foreground: "assets/logo_plain.jpg"
#  adaptive_icon_foreground_inset: 0
#  windows:
#    generate: true
#    image_path: "assets/logo_plain.jpg"
#    icon_size: 48 # min:48, max:256, default: 48
  # ------------------------------------
#launcher_name:
#  default: "Infinity"
# --------------------------------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banner.jpg
    - assets/icon.png
    - assets/icon_white.png
    - assets/logo.jpg
    - assets/name.png
  # --------------------------------------------------------------------------------
  fonts:
    - family: madani_thin
      fonts:
        - asset: assets/fonts/madani_arabic_thin.ttf
    - family: madani_extra_light
      fonts:
        - asset: assets/fonts/madani_arabic_extra_light.ttf
    - family: madani_light
      fonts:
        - asset: assets/fonts/madani_arabic_light.ttf
    - family: madani_regular
      fonts:
        - asset: assets/fonts/madani_arabic_regular.ttf
    - family: madani_medium
      fonts:
        - asset: assets/fonts/madani_arabic_medium.ttf
    - family: madani_semi_bold
      fonts:
        - asset: assets/fonts/madani_arabic_semi_bold.ttf
    - family: madani_bold
      fonts:
        - asset: assets/fonts/madani_arabic_bold.ttf
    - family: madani_extra_bold
      fonts:
        - asset: assets/fonts/madani_arabic_extra_bold.ttf
    - family: madani_black
      fonts:
        - asset: assets/fonts/madani_arabic_black.ttf
    - family: madani_variable
      fonts:
        - asset: assets/fonts/madani_arabic_variable.ttf
    - family: montreal
      fonts:
        - asset: assets/fonts/montreal.ttf
# --------------------------------------------------------------------------------